language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - "tip"
install:
  - mkdir -p $HOME/gopath/src/gopkg.in/Darigaaz
  - mv $HOME/gopath/src/github.com/Darigaaz/logrus-airbrake-hook $HOME/gopath/src/gopkg.in/Darigaaz/logrus-airbrake-hook.v4
  - cd $HOME/gopath/src/gopkg.in/Darigaaz/logrus-airbrake-hook.v4
  - go get -t
