language: go
go:
  - 1.3
  - 1.4
  - 1.5
  - tip
install:
  - mkdir -p $HOME/gopath/src/gopkg.in
  - mv $HOME/gopath/src/github.com/gemnasium/logrus-airbrake-hook $HOME/gopath/src/gopkg.in/gemnasium/logrus-airbrake-hook.v2
  - cd $HOME/gopath/src/gopkg.in/gemnasium/logrus-airbrake-hook.v2
